version: ENC[AES256_GCM,data:YVbRU2pH,iv:KxPV5CF1U2oREWz1gLwKAgjScXgP7y5HOj5nMM7FEaE=,tag:3+P69G38TujezLv4NL2AwQ==,type:str]
cache: ENC[AES256_GCM,data:CSqhlA==,iv:zaJhXB/XtVRBIIveIkw1AoE7+CZR7ukZUN7L/8ImUkE=,tag:urt+GVcioDZgK+w1tfm4Kg==,type:bool]
endpoints:
    custom:
        - name: ENC[AES256_GCM,data:9buo96bLdy8=,iv:ElIpcRga5jASDyxPeZCbxBlejV5o57jrun4v9/Ag8Dk=,tag:6CP6FyUfS37TWDX7og86tA==,type:str]
          apiKey: ENC[AES256_GCM,data:A6Hy5APzOvdlYk99HyYobQIM/A==,iv:jR73kZdDSf+RE6jZ5j9Pvbd+vXgv9nzEjzcQ3RuATis=,tag:0s2IID08PH27auFS1L9Axg==,type:str]
          baseURL: ENC[AES256_GCM,data:yn6WVVPKV82yWn55ljMn5ziN63JC+H9vPYUc,iv:f8ZZ3pmKslLHPAHKmMMCCmdYUBQanHex4MC8c0TIcMI=,tag:HZM4vwHIueGPPINXhsanVw==,type:str]
          modelDisplayLabel: ENC[AES256_GCM,data:46jDE/mYUu4=,iv:E797/GXZnNEZBG4GmrnbOvsHMvK6092sEBaITvLAy7s=,tag:FUvgMgwSc2WuGpPC443Y7g==,type:str]
          titleConvo: ENC[AES256_GCM,data:9ZykoA==,iv:BdmXXH+Q3mIs+nPqa+DMEZl1ELPqJ+ZE9MP0IEBprzo=,tag:n77RtxfHamLrSF61ZM5fvA==,type:bool]
          titleModel: ENC[AES256_GCM,data:DqQ2EBQSSq509EHcuGaTFrc=,iv:oXM2KNe2Z/ELYCI9NvTajeX6ECJj20rgsm4Es/myzuY=,tag:R80SXAPYAzpR51yVsaSqVQ==,type:str]
          models:
            fetch: ENC[AES256_GCM,data:H/DSYg==,iv:oBZsgR7hImD5xgaw4TcQTv2EpqElBZZJSrUB6OWOx0o=,tag:w4RYT3I7QEgc/4NxXKNU2w==,type:bool]
            default:
                - ENC[AES256_GCM,data:p8AzQIxepM8nwPlwLShUV70=,iv:awl3pwT4DerY4kwowtqyhkmPTLJ6bRDUPoINXuiexyI=,tag:uGfuw1e4ytWmFwTEWVvBFA==,type:str]
        - name: ENC[AES256_GCM,data:AaXlaAoge5JKuZQ=,iv:3zQxUaK8nX8BhgivuK+9fB+rQKlL9+hpRoEIkv2dmV0=,tag:LUS4JNViZ/fQudBQvKC4vw==,type:str]
          apiKey: ENC[AES256_GCM,data:hgrcFPoELayWnSV0tR/n1hyv2A==,iv:d9Y54tTy7veowrbvNcnqtO8I/zvM3OGpmvIGWsYIuLo=,tag:19EyooT1Pk1HuKNSDo2Qlw==,type:str]
          baseURL: ENC[AES256_GCM,data:YewsqQR3sCgLXqTq5DeSbqTE0Ir3lS8cM2bPB3s=,iv:lHk92DDEcRr1wXSBNi6DgNUES34zjajHeIkjjzvg2SQ=,tag:3VLVrKR1TyFHumB9GMJVcA==,type:str]
          modelDisplayLabel: ENC[AES256_GCM,data:v/b2jr40xYG+GGs=,iv:vNAJP6wVcOOMJWOMUD6feC9k6NMds4nXBwkMJIznA38=,tag:IHy7fayRyc2X4TZux92c0w==,type:str]
          titleConvo: ENC[AES256_GCM,data:6cDClA==,iv:XLGQouicFzN8kdJfp+chSe/xqHi3zO/Pz3OUEu4okOo=,tag:p+MwhXQfmigVRtToqeP1ww==,type:bool]
          titleModel: ENC[AES256_GCM,data:C2k9rqy2mvmKVZ5PnIvMlP4=,iv:I3mkOORaR9aRg6wH4w2lSMVotg+MwR7RjDR6IpT2qLo=,tag:4lo4nUHXZYj7Z9gi1epuYQ==,type:str]
          models:
            fetch: ENC[AES256_GCM,data:yyiqgg==,iv:dvVVBZRhtUiivsENTGgeE+Hf8ERNVgYOUq+2u7pVrEE=,tag:TTovEUZPe14uD11zaocENw==,type:bool]
            default:
                - ENC[AES256_GCM,data:RlRAYfnX1BDPJOdxdI8deQE=,iv:CdRzvzIbsAWBVI73XK+nVjZx2vJXA8WXeyYOQ15x0yk=,tag:g5/rsEn8kWUhq+pEPBEF5A==,type:str]
        - name: ENC[AES256_GCM,data:SD4rY7rT5ah4vw==,iv:34tZu85vqHZK4C4u7COv0vIURrCSeWcWFoGR3p6nFH8=,tag:WJMER3NX+GAezft9cn04wg==,type:str]
          apiKey: ENC[AES256_GCM,data:1YWAdNQ1uT14SyS7kbrwrdg=,iv:mmL/GDP/on5Oa9LQIICsnv3I2SIMi9/Z+WBJnLJF87s=,tag:Gs3XB6mACcn93aXGo+mShQ==,type:str]
          baseURL: ENC[AES256_GCM,data:LNiyEfzKgm+xBM+WLcXuvyEvrxo5+g8Qp9jbEg==,iv:W02V+FnW9S0lLeHhY3PhzLQ+0Me8ZhyriRFaOF334ps=,tag:tZEYSlkTadWYpJjRqKGdBA==,type:str]
          modelDisplayLabel: ENC[AES256_GCM,data:Cr1nVX1LQZyiQg==,iv:2ZbbDowS8SCEZhyUGlaBZOIJQOWqHPIPbh9j9k6K038=,tag:V82FXHKQARuRp8l/T6my1g==,type:str]
          titleConvo: ENC[AES256_GCM,data:ooEGww==,iv:y8FH1uvvBix2dfjZNu2UigxkRbvrYTQRA4QwaLY0awQ=,tag:kQUA4VnZCqFqPtSCAJ0uzw==,type:bool]
          titleModel: ENC[AES256_GCM,data:3yzPsoZe4BQ2yuv28irfkSF2zJG0Yhc+ELg=,iv:PjFgI0ViUIk39BhApIrCyH1juB/szwVm5U6RVHFc27s=,tag:zQ4feIAyAqhavNbNHpHICQ==,type:str]
          dropParams:
            - ENC[AES256_GCM,data:TWBM7g==,iv:PrCMqb9ZTohYO0ZC5ku+WNB8IaafQnKZ4rgunozeXWs=,tag:u2wQX9mg8kUXX/Ghu0bAsQ==,type:str]
          models:
            fetch: ENC[AES256_GCM,data:RohA5Q==,iv:E3DmaSICkd0E/efjlkyjNlOxU6M2vvGZx+eZQoR1ZsI=,tag:pue/pwosalqRK0ET6wsFMA==,type:bool]
            default:
                - ENC[AES256_GCM,data:Kk//ALmS8xLxA3OBg8koSdYnrMfiwUl9tqQ=,iv:tljh0T9QYwGwG+l7pkRlozf4/gULvM439BtCFFRYPG8=,tag:oknOLe1Vp8Dea90zrWmpxA==,type:str]
mcpSettings:
    allowedDomains:
        - ENC[AES256_GCM,data:qJktDZIUNpeZVQ==,iv:LNSvAEmukA5JrBcjGdwX3wksIhslf/qzlcMNZZqqCBA=,tag:xuBni02yTtIwCoKyM61ISQ==,type:str]
        - ENC[AES256_GCM,data:flXVyvGn6WqQBQ/i,iv:y8zf+x3D7vbIIqwySVMRu0cuw0jntMk6N/yue8sImzg=,tag:l3S9Z/eZ526KjlMuaG2cWw==,type:str]
        - ENC[AES256_GCM,data:r7nulyMlnE7Fix73MQ==,iv:Bd7k95yrRDn48VBoCA1rS6aRHsBSc8Zl/hLCg1dP5Mo=,tag:3HU8Dt6YyC1MRdeolIrCWQ==,type:str]
        - ENC[AES256_GCM,data:wq7Av8YG8mjoBB+RDs1p,iv:UR9eYrpRA5PukFZBil0+9xAabEYAJrgGtHYWffkVAlo=,tag:RWMxDyGWOWq86TVjc/AWvw==,type:str]
        - ENC[AES256_GCM,data:fKSor6UAY2KFsA==,iv:slmDUInOZPzCKi9J7Q7VPYGk/uhNAV5ZwMHRkhYMl2I=,tag:9MzTu4NuN9+pE4WpWh09vg==,type:str]
        - ENC[AES256_GCM,data:CvczTcMRInSAINeZ,iv:l2v7KOCx27C9KEFdumtAuIS3a8M9ywG9nSTLL5YEp9Y=,tag:Q6agLUx2ao2OjYc2+zJ0oQ==,type:str]
        - ENC[AES256_GCM,data:nlo9d6l27+dkmw==,iv:j1mytNsFs4xG4coaVycVw2G+WJN+Ogum74rtiFeEMMs=,tag:3FA52IPUtIU1aaF6w7TgTA==,type:str]
        - ENC[AES256_GCM,data:tro9vtqQVjGZZ+Ud,iv:SxBzOYicURYBwjv7OCuDL+2vYJ7cz/ng6iE+cJYwOLw=,tag:la0Ns+OakXN22KwhYXX75g==,type:str]
        - ENC[AES256_GCM,data:bOzCfKpfRFs7aw==,iv:fjMcSeK7wsOmRmu6kTGkMCjOUJHvvJ8gK3xJZavf0Jw=,tag:rlp78BdnwymQLpaV8eVirQ==,type:str]
        - ENC[AES256_GCM,data:xFSpm38euEYlVTMD,iv:hYpuprJjVaC2y0D7GgjeqCub2hPRvefC10doRwwkSuA=,tag:uoHUtV0S1NS1FGoeYMLJFA==,type:str]
        - ENC[AES256_GCM,data:zaGmLG2TTbKK8g==,iv:eO0RxwGTOMLF9HtthFwyNT19cB0rD0gbNKOHGqOOy3U=,tag:skA6tCXcI/OvVcULM91ltA==,type:str]
        - ENC[AES256_GCM,data:NIxf1UMdzPS0JP2P,iv:7SBEhash3q3yRiu/rA+53MkyysibwGBRmF+ildsi0UE=,tag:ajYPFlA7ZhFceALGs3Yhng==,type:str]
        - ENC[AES256_GCM,data:CgtqCj6/6alX5CEhAQ==,iv:OE79QBRX9aTpy9APPcEnTznANVXHQRostC/txelEqRA=,tag:sf5cDTTnjhf2S0Udt0SVdQ==,type:str]
        - ENC[AES256_GCM,data:Io31yrkc27Jnlglfz5rA,iv:lqfpb6aEzwDPyQv9tL3yLcbXWLf2u1hObwobkeHHLVc=,tag:XML6t4RAVvwnFwMeA+TUZw==,type:str]
        - ENC[AES256_GCM,data:cLZN+ZLPy0c6Qc0=,iv:8ZoCmcamJySzqzbGFIi75qtWO1ZWJxGvcehrEAhrAP0=,tag:5qN9bdX181NxYlWqgTMyNQ==,type:str]
        - ENC[AES256_GCM,data:zMTseAkyIMRFm2WeLQ==,iv:vMAIPh1cyUCRa7wflD25Yk/6i//s7kINbLjtm5lXH/Q=,tag:5pWop8QTtdQrVdim/jKtBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudDZqTVRiWUpva2w4SmtH
            Rk9kNm8va05Ka0pWM3hZcE1mdlc3MVpMM24wClhKemVjM2dwM0FUb0hnU0lUTElG
            VUl3aHltZnN5bUZCMnNuY1ZKdnVJRXcKLS0tIHFTeTAycVkwZDMwbnFXTmFuTlc2
            RVN4LzlsbStmZXd2eUZkY1F3M0h4QmcK/OlJi5hZOj9PL/XnyR+YnlsPqbuUCs0m
            AtTkM6JaWzhOPN4sYBMt9MHHDrXxgcyyaaOxlFKYsbq1TbhF4j9xog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1efn67qrhcfhdjycg0sckmnpytcm765ndwys0zfg8dth2lqqss93qk8tsjd
    lastmodified: "2026-06-12T04:59:37Z"
    mac: ENC[AES256_GCM,data:9SH6Rm8/FHVDmCK+XQitImfodT8SRyikvMtq6VGi1TyHd+p8hsvd9yINEuqCseuxdvuD+te2T+YboIAhMPhI4rx8L+jyKgXNXRxtn/V4qIBiCa/NquGkdmfa8jTXpax6wjCdw4J5f6dciTrQ0srPOKwIw8pL72GBu7Yo0sjU5Nw=,iv:AdZ9/VZ3AEMd+dfu0gD0iZnsNhe9f1iAp61BU67r1mQ=,tag:THgMeoFCmEPAIUJaa54vgQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
