{
	"data": "ENC[AES256_GCM,data:77MnJ0cy28sM9nApuF9z8okmel9Nm3owChMH0M9Nt1L8o+eDcCgcafBzJA==,iv:VMWJd/3B1ZKVFCZqid/lTSU79wy+Pd4cLSCPq9VoIhY=,tag:2gByQMis0RhMPghcC4OZ4Q==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRm9ybmYwUHhudEF1bkVG\nWHFHdzZKYXowSDltOEV5cXVvcnI1b3lWcWdNCkVpVThPTWM2NnJIVyswNHVydFRI\nSGZrMFVyZmI0ZWhNbVFBWHIyN240SkUKLS0tIEgvbktoVFNEVDVvTlVCUGZob0lB\nWlJSWVBSdzE3TURWQmJVaUJMaG52YTAK1uKMrNj7KW8U6LsBAf26hxEio+Cr7fU2\nmiLVqIyrH6E2yvNPIANBVqKJgT2r3NyznSeqdGW7yu902YXj4fw8EQ==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1efn67qrhcfhdjycg0sckmnpytcm765ndwys0zfg8dth2lqqss93qk8tsjd"
			}
		],
		"lastmodified": "2026-07-24T02:16:50Z",
		"mac": "ENC[AES256_GCM,data:ovvQ98Wju0xH98VluMawVqmB8s31yLgmuyBnA8IqulArbdYOr1PqMiEa1HW/59w6EHs7Q7Dy2aUH/5uZ1ASDsWr+XTkuVILfad6ZM7yIdTGWNeCI/rXRbex+hp94ienCCMUTmolYCaDFzdnP+nqbT22JHd0S1uPr3DntPiKhaao=,iv:rinRe1ixQJPTV/u7OB2O9w1K1pG68shGYbMJMm4gOKU=,tag:MLfpwbf7nuFcao7YixrNXA==,type:str]",
		"version": "3.13.2"
	}
}
