{
	"data": "ENC[AES256_GCM,data:luKDXzEi/re3iV/dayFqlX5s9KTRXSjBDdAuNX08Hz+ZBpSvvePI4x9Y58/Ok6B50MjTaDdX2y4ri2VRKA==,iv:oJaT9w7/pPOgewxrL8IC/OT+RnC2ue+gwZvo+5JyZuY=,tag:XP+wDfkL2F8NL0wkxBUAcA==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNVhXakJrZXBmb0JyNGp4\nUVh2U0JlZTFGUlliU3J4bUdLeWNmTGllQXlNCk9ramptUXcyU05iSjBPQjJ4ai8x\nUW5qaDFXK0twQzNWQ0Uwbmt3TXpNK1EKLS0tIFFtN25hQ1gxaE01K0pDWmxVdFk2\naVQzdEs3aWhlbnJxUC9VM3p0enFZNE0KBLPDzVcSS9x3DQqVG9HFhdhCFmN26ORb\nUZzlYuZlpsYZonVbG8hP0pF6ZnzqzAnNZSScNFbSm3sk7KoXK6b9nA==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1efn67qrhcfhdjycg0sckmnpytcm765ndwys0zfg8dth2lqqss93qk8tsjd"
			}
		],
		"lastmodified": "2026-07-24T02:16:50Z",
		"mac": "ENC[AES256_GCM,data:N7Iy8wN3yimii7UZJu4c1lgJyQY2LD/8z4216ZadU7IcTiGdVKCm3QGe6RvihIYzzxr9wCTvsCPx2Vqr0oD53C4Qay+QSb4em8Q/surP7nHhQ7v6LM8ggXQNxPyOgAqlI07ZjpjBBewP+8JpZ54vx9NP1zqSm/ZgjjOunG696oc=,iv:gMH5oQjRWeloalR3T0BppCvcBlZ5TzdYFoNdBLTF3l4=,tag:KIKVqAVXCaMACoQ21Np/7w==,type:str]",
		"version": "3.13.2"
	}
}
